In [1]:
import pandas as pd

In [5]:
# ser_obj = pd.Series(range(10))
# 通过 list 构建 Series
ser_obj = pd.Series(range(10, 20))
print(ser_obj.head(3))
print(ser_obj)
print(type(ser_obj))

0    10
1    11
2    12
dtype: int64
0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
<class 'pandas.core.series.Series'>


In [6]:
# 获取数据
print(ser_obj.values)
# 获取索引
print(ser_obj.index)

[10 11 12 13 14 15 16 17 18 19]
RangeIndex(start=0, stop=10, step=1)


In [7]:
#通过索引获取数据
print(ser_obj[0])
print(ser_obj[8])

10
18


In [9]:
# 索引与数据的对应关系不被运算结果影响
print(ser_obj * 2)
print('-'*60)
print(ser_obj > 15)

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
------------------------------------------------------------
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [10]:
# 通过 dict 构建 Series
year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2.head())
print('-'*60)
print(ser_obj2.index)
print('-'*60)
print(ser_obj2[2001])

2001    17.8
2002    20.1
2003    16.5
dtype: float64
------------------------------------------------------------
Index([2001, 2002, 2003], dtype='int64')
------------------------------------------------------------
17.8


In [11]:
# name 属性
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year'
print(ser_obj2.head())

year
2001    17.8
2002    20.1
2003    16.5
Name: temp, dtype: float64


In [13]:
import numpy as np
import pandas as pd
# 通过 ndarray 构建 DataFrame
t = pd.DataFrame(np.arange(12).reshape((3,4)))
print(t)
print('-'*60)
array = np.random.randn(5,4)
print(array)
print('-'*60)
df_obj = pd.DataFrame(array)
print(df_obj.head())

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
------------------------------------------------------------
[[ 0.88316555 -0.48585308 -0.62436236 -0.61978389]
 [-0.71015481 -0.27731315 -0.80872414  0.53064167]
 [ 1.03818407  1.35150928 -0.23601991  0.47493262]
 [ 0.66587793  0.08399068  1.50598976  1.84182518]
 [ 0.81320656  0.37520945 -0.56882984 -1.83362671]]
------------------------------------------------------------
          0         1         2         3
0  0.883166 -0.485853 -0.624362 -0.619784
1 -0.710155 -0.277313 -0.808724  0.530642
2  1.038184  1.351509 -0.236020  0.474933
3  0.665878  0.083991  1.505990  1.841825
4  0.813207  0.375209 -0.568830 -1.833627


In [14]:
# 通过 dict 构建 DataFrame
import pandas as pd
import numpy as np
dict_data = {'A': 1,
'B': pd.Timestamp('20190926'),
'C': pd.Series(1,
index=list(range(4)),dtype='float32'),
'D': np.array([3] * 4,dtype='int32'),
'E': ["Python","Java","C++","C"],
'F': 'wangdao' }
#print dict_data
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)
print('-' * 60)
d1={"name":["xiaoming","xiaogang"],"age":[20,32],"tel":
[10086,10010]}
print(pd.DataFrame(d1))
d2 =[{"name" : "xiaohong" ,"age" :32,"tel" :10010},{ "name":
"xiaogang" ,"tel": 10000} ,{"name":"xiaowang" ,"age":22}]
print('-' * 60)
print(pd.DataFrame(d2))

   A          B    C  D       E        F
0  1 2019-09-26  1.0  3  Python  wangdao
1  1 2019-09-26  1.0  3    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  3       C  wangdao
------------------------------------------------------------
       name  age    tel
0  xiaoming   20  10086
1  xiaogang   32  10010
------------------------------------------------------------
       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN


In [16]:
# 通过列索引获取列数据(在 3.2 的代码增加即可)
print(df_obj2['A'])
print('-' * 60)
print(type(df_obj2['A']))
print('-' * 60)
print(df_obj2.A)

0    1
1    1
2    1
3    1
Name: A, dtype: int64
------------------------------------------------------------
<class 'pandas.core.series.Series'>
------------------------------------------------------------
0    1
1    1
2    1
3    1
Name: A, dtype: int64


In [17]:
# 增加列
df_obj2['G'] = df_obj2['D'] + 4
print(df_obj2.head())

   A          B    C  D       E        F  G
0  1 2019-09-26  1.0  3  Python  wangdao  7
1  1 2019-09-26  1.0  3    Java  wangdao  7
2  1 2019-09-26  1.0  3     C++  wangdao  7
3  1 2019-09-26  1.0  3       C  wangdao  7


In [18]:
# 删除列
del(df_obj2['G'] )
print(df_obj2.head())

   A          B    C  D       E        F
0  1 2019-09-26  1.0  3  Python  wangdao
1  1 2019-09-26  1.0  3    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  3       C  wangdao


In [19]:
import pandas as pd
import numpy as np
dict_data = {'A': 1,
'B': pd.Timestamp('20190926'),
'C': pd.Series(1,
index=list(range(4)),dtype='float32'),
'D': np.array([3] * 4,dtype='int32'),
'E': ["Python","Java","C++","C"],
'F': 'wangdao' }
#print dict_data
df_obj2 = pd.DataFrame(dict_data)
ser_obj = pd.Series(range(10, 20))
print(type(ser_obj.index))
print(type(df_obj2.index))
print(df_obj2.index)

<class 'pandas.core.indexes.range.RangeIndex'>
<class 'pandas.core.indexes.base.Index'>
Index([0, 1, 2, 3], dtype='int64')


In [20]:
ser_obj = pd.Series(range(5), index = ['a', 'b', 'c', 'd', 'e'])
print(ser_obj.head())

a    0
b    1
c    2
d    3
e    4
dtype: int64


In [21]:
print(ser_obj['b'])
print(ser_obj[2])

1
2


C:\Users\ttx\AppData\Local\Temp\ipykernel_20984\3227646668.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(ser_obj[2])


In [22]:
print(ser_obj[1:3])
print(ser_obj['b':'d'])

b    1
c    2
dtype: int64
b    1
c    2
d    3
dtype: int64


In [23]:
# 不连续索引
print(ser_obj[[0, 2, 4]])
print(ser_obj[['a', 'e']])

a    0
c    2
e    4
dtype: int64
a    0
e    4
dtype: int64


C:\Users\ttx\AppData\Local\Temp\ipykernel_20984\1727138288.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(ser_obj[[0, 2, 4]])


In [24]:
# 布尔索引
ser_bool = ser_obj > 2
print(ser_bool)
print(ser_obj[ser_bool])
print(ser_obj[ser_obj > 2])

a    False
b    False
c    False
d     True
e     True
dtype: bool
d    3
e    4
dtype: int64
d    3
e    4
dtype: int64


In [25]:
import numpy as np
df_obj = pd.DataFrame(np.random.randn(5,4), columns = ['a', 'b', 'c', 'd'])
print(df_obj.head())

          a         b         c         d
0 -0.136054  0.960042 -0.306397  0.393265
1 -0.455560 -0.069358 -0.032305  0.095712
2  0.743399  0.263210  0.037049 -2.033507
3 -0.817042  0.709652  2.730556 -0.362622
4 -0.704903 -1.567632  0.991969 -0.736764


In [26]:
print(df_obj['a']) # 返回 Series 类型
print(df_obj[['a']]) # 返回 DataFrame 类型
print(type(df_obj[['a']])) # 返回 DataFrame 类型

0   -0.136054
1   -0.455560
2    0.743399
3   -0.817042
4   -0.704903
Name: a, dtype: float64
          a
0 -0.136054
1 -0.455560
2  0.743399
3 -0.817042
4 -0.704903
<class 'pandas.core.frame.DataFrame'>


In [27]:
# 不连续索引
print(df_obj[['a','c']])

          a         c
0 -0.136054 -0.306397
1 -0.455560 -0.032305
2  0.743399  0.037049
3 -0.817042  2.730556
4 -0.704903  0.991969


In [28]:
# 标签索引 loc
# Series
print(ser_obj['b':'d'])
print(ser_obj.loc['b':'d'])
# DataFrame
print(df_obj['a'])
# 第一个参数索引行，第二个参数是列
print(df_obj.loc[0:2, 'a'])

b    1
c    2
d    3
dtype: int64
b    1
c    2
d    3
dtype: int64
0   -0.136054
1   -0.455560
2    0.743399
3   -0.817042
4   -0.704903
Name: a, dtype: float64
0   -0.136054
1   -0.455560
2    0.743399
Name: a, dtype: float64


In [29]:
# 整型位置索引 iloc
# Series
print(ser_obj[1:3])
print(ser_obj.iloc[1:3])
# DataFrame
print(df_obj.iloc[0:2, 0]) # 注意和 df_obj.loc[0:2, 'a']的区别

b    1
c    2
dtype: int64
b    1
c    2
dtype: int64
0   -0.136054
1   -0.455560
Name: a, dtype: float64


In [31]:
s1 = pd.Series(range(10, 20), index = range(10))
s2 = pd.Series(range(20, 25), index = range(5))
print('s1: ' )
print(s1)
print('')
print('s2: ')
print(s2)

s1: 
0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

s2: 
0    20
1    21
2    22
3    23
4    24
dtype: int64


In [32]:
# Series 对齐运算
print('s1+s2: ')
print(s1+s2)

s1+s2: 
0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64


In [33]:
df1 = pd.DataFrame(np.ones((2,2)), columns = ['a', 'b'])
df2 = pd.DataFrame(np.ones((3,3)), columns = ['a', 'b', 'c'])
print('df1: ')
print(df1)
print('')
print('df2: ')
print(df2)

df1: 
     a    b
0  1.0  1.0
1  1.0  1.0

df2: 
     a    b    c
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0


In [34]:
# DataFrame 对齐操作
print('df1+df2: ')
print(df1+df2)

df1+df2: 
     a    b   c
0  2.0  2.0 NaN
1  2.0  2.0 NaN
2  NaN  NaN NaN


In [35]:
print(s1)
print(s2)
print(s1.add(s2, fill_value = 0))
print(df1)
print(df2)
print(df1.sub(df2, fill_value = 2.))

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
0    20
1    21
2    22
3    23
4    24
dtype: int64
0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5    15.0
6    16.0
7    17.0
8    18.0
9    19.0
dtype: float64
     a    b
0  1.0  1.0
1  1.0  1.0
     a    b    c
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0
     a    b    c
0  0.0  0.0  1.0
1  0.0  0.0  1.0
2  1.0  1.0  1.0


In [36]:
# Numpy ufunc 函数
df = pd.DataFrame(np.random.randn(5,4) - 1)
print(df)
print(np.abs(df))

          0         1         2         3
0  0.823683 -0.228022 -0.822608 -0.494135
1 -2.641908 -1.526394 -1.142154 -1.056315
2 -0.253609  1.253175 -3.056220 -0.366651
3 -1.310455 -0.008568 -0.156587 -1.378581
4 -1.510522 -1.008970 -2.450005  0.457785
          0         1         2         3
0  0.823683  0.228022  0.822608  0.494135
1  2.641908  1.526394  1.142154  1.056315
2  0.253609  1.253175  3.056220  0.366651
3  1.310455  0.008568  0.156587  1.378581
4  1.510522  1.008970  2.450005  0.457785


In [37]:
# 使用 apply 应用行或列数据（接上面代码）
#f = lambda x : x.max()
print(df.apply(lambda x : x.max()))

0    0.823683
1    1.253175
2   -0.156587
3    0.457785
dtype: float64


In [38]:
# 指定轴方向，axis=1，方向是行
print(df.apply(lambda x : x.max(), axis=1))

0    0.823683
1   -1.056315
2    1.253175
3   -0.008568
4    0.457785
dtype: float64


In [39]:
# 使用 map 应用到每个数据
f2 = lambda x : '%.2f' % x
print(df.map(f2))

       0      1      2      3
0   0.82  -0.23  -0.82  -0.49
1  -2.64  -1.53  -1.14  -1.06
2  -0.25   1.25  -3.06  -0.37
3  -1.31  -0.01  -0.16  -1.38
4  -1.51  -1.01  -2.45   0.46


In [40]:
import numpy as np
import pandas as pd
df_obj = pd.DataFrame(np.random.randn(5,4), columns = ['a', 'b', 'c', 'd'])
print(df_obj)

          a         b         c         d
0  1.248404 -1.129972  1.222450  0.232455
1  0.582266 -0.896852  0.600357  0.172995
2 -1.725244  1.407341  0.523373 -1.185899
3 -0.384467  0.142463  0.497452 -0.258779
4  1.228685  0.416050 -0.177251  0.430539


In [41]:
df_obj.sum()
df_obj.max()
df_obj.min(axis=1, skipna=False)

0   -1.129972
1   -0.896852
2   -1.725244
3   -0.384467
4   -0.177251
dtype: float64

In [42]:
print(df_obj.describe())

              a         b         c         d
count  5.000000  5.000000  5.000000  5.000000
mean   0.189929 -0.012194  0.533276 -0.121738
std    1.260072  1.031315  0.496410  0.645862
min   -1.725244 -1.129972 -0.177251 -1.185899
25%   -0.384467 -0.896852  0.497452 -0.258779
50%    0.582266  0.142463  0.523373  0.172995
75%    1.228685  0.416050  0.600357  0.232455
max    1.248404  1.407341  1.222450  0.430539
