In [2]:
import numpy as np
import random

In [3]:
f = np.array([1, 2, 3, 4, 5])
print(f.itemsize) # 每个元素的字节大小
print(f.dtype) # 数据类型

8
int64


In [4]:
random.random() * 10 # 生成0-10之间的随机浮点数

9.16079909852918

# 数组和数的计算

In [5]:
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((1, 6))
print(t1)
print(t2)

t1 - t2 #

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1 2 3 4 5]]


array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

In [7]:
# 请你给出三维的例子
t3 = np.arange(24).reshape((2, 3, 4))
t4 = np.arange(4).reshape((1, 1, 4))
print(t3)
print(t4)

t3 - t4

#

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[0 1 2 3]]]


array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

请你总结上述广播机制的规则
1. 如果两个数组的维度数不同，那么维度较少的数组会在前面补1，直到两个数组的维度数相同。
2. 如果两个数组在某个维度上的长度不同，但其中一个数组在该维度上的长度为1，那么该数组会沿着该维度进行扩展，以匹配另一个数组的长度。
3. 如果两个数组在某个维度上的长度都不相同且都不为1，那么会引发错误，表示无法进行广播。
4. 广播机制允许在不复制数据的情况下进行数组运算，从而提高计算效率。
5. 广播机制适用于各种算术运算，如加法、减法、乘法和除法等。
6. 广播机制在处理多维数组时尤为有用，能够简化代码并提高可读性。
7. 理解广播机制有助于更好地利用NumPy进行高效的数值计算。
8. 广播机制不仅适用于数组与数组之间的运算，也适用于数组与标量之间的运算。
9. 广播机制在数据分析和科学计算中广泛应用，是NumPy的核心特性之一。
10. 掌握广播机制有助于优化代码性能，减少内存使用，提高计算速度。
11. 广播机制在处理不同形状的数组时提供了灵活性，使得代码更加简洁和易于维护。

In [10]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("-" * 20)
print(np.sum(a, axis=0)) # 列求和,结果是每一列的和,返回一个一维数组,长度等于列数
print("-" * 20)
print(np.sum(a, axis=1)) # 行求和,结果是每一行的和,返回一个一维数组,长度等于行数


[[1 2 3]
 [4 5 6]]
--------------------
[5 7 9]
--------------------
[ 6 15]


In [17]:
a = np.arange(24).reshape(2, 3, 4)
b = np.sum(a, axis=0)
print(a)
print("-" * 20)
# print(b.shape) # (3, 4)
# print(b)
# c = np.sum(a, axis=1)
# print("-" * 20)
# print(c.shape) # (2, 4)
# print(c)
d = np.sum(a, axis=2)
print("-" * 20)
print(d.shape) # (2, 3)
print(d)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------------
--------------------
(2, 3)
[[ 6 22 38]
 [54 70 86]]


In [19]:
# import numpy as np

# 创建一个形状为 (2, 2, 2, 2) 的四维数组
# 可以理解为：2个大组，每个大组里有2张表，每张表是2x2
a = np.arange(16).reshape(2, 2, 2, 2)

# 执行 axis=0 降维求和
b = np.sum(a, axis=0)

print(a)
print("-" * 20)
print("Shape after summing over axis 0:", b.shape)  # 结果形状应为 (2, 2, 2)
print(b)
print("-" * 20)
# 执行 axis=1 降维求和
c = np.sum(a, axis=1)
print("Shape after summing over axis 1:", c.shape)  # 结果形状应为 (2, 2, 2)
print(c)
print("-" * 20)
# 执行 axis=2 降维求和
d = np.sum(a, axis=2)
print("Shape after summing over axis 2:", d.shape)  # 结果形
print(d)
print("-" * 20)
# 执行 axis=3 降维求和
e = np.sum(a, axis=3)
print("Shape after summing over axis 3:", e.shape)  # 结果形
print(e)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
--------------------
Shape after summing over axis 0: (2, 2, 2)
[[[ 8 10]
  [12 14]]

 [[16 18]
  [20 22]]]
--------------------
Shape after summing over axis 1: (2, 2, 2)
[[[ 4  6]
  [ 8 10]]

 [[20 22]
  [24 26]]]
--------------------
Shape after summing over axis 2: (2, 2, 2)
[[[ 2  4]
  [10 12]]

 [[18 20]
  [26 28]]]
--------------------
Shape after summing over axis 3: (2, 2, 2)
[[[ 1  5]
  [ 9 13]]

 [[17 21]
  [25 29]]]


# 索引和切片