In [1]:
import numpy as np


In [2]:
# 请你解释下面代码的作用
# 将一个普通的Python列表转换为NumPy数组
# 创建一个包含整数1到4的列表
list1 = [1,2,3,4]
oneArray = np.array(list1)
print(type(oneArray))
print(oneArray)

<class 'numpy.ndarray'>
[1 2 3 4]


In [3]:
t1 = np.array([1,2,3])
print(t1)
print(type(t1))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
t2 = np.array(range(10))
print(t2)
print(type(t2))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [5]:
t3 = np.arange(0,10,2)
print(t3)
print(type(t3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [6]:
list2 = [[1,2],[3,4],[5,6]]
twoArray = np.array(list2)
print(twoArray)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
list2 = [[1,2],[3,4],[5,6]]
twoArray = np.array(list2)
# 获取数组的维度( 注意： 与函数的参数很像)
print(twoArray.ndim)
# 形状（行，列）
print(twoArray.shape)
# 有多少个元素
print(twoArray.size)

2
(3, 2)
6


In [9]:
four = np.array([[1,2,3],[4,5,6]])
# 修改的是原有的
four.shape = (3,2)
print(four)
print("-" * 50)
# 返回一个新的数组
four = four.reshape(3,2)
print(four)
print("-" * 50)
# 将多维变成一维数组
five = four.reshape((6,),order='F')
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six = four.flatten(order='F')
print(five)
print("-" * 50)
print(six)
print("-" * 50)
# 拓展：数组的形状
t = np.arange(24)
print(t)
print(t.shape)
print("-" * 50)
# 转换成二维
t1 = t.reshape((4,6))
print(t1)
print(t1.shape)

[[1 2]
 [3 4]
 [5 6]]
--------------------------------------------------
[[1 2]
 [3 4]
 [5 6]]
--------------------------------------------------
[1 3 5 2 4 6]
--------------------------------------------------
[1 3 5 2 4 6]
--------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
--------------------------------------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


In [10]:
a= np.array([9, 12, 88, 14, 25])
list_a = a.tolist()
print(list_a)
print(type(list_a))

[9, 12, 88, 14, 25]
<class 'list'>


In [11]:
import random
# 返回数组中每个元素的字节单位长度，dtype设置数据类型
f = np.array([1,2,3,4,5], dtype = np.int16)
print(f.itemsize) # 1 np.int8(一个字节)
# 获取数据类型
print(f.dtype)
# 调整数据类型
f1 = f.astype(np.int64)
print(f1.dtype)
# 拓展随机生成小数
# 使用python语法，保留两位
print(round(random.random(),2))
arr = np.array([random.random() for i in range(10)])
# 取小数点后两位
print(np.round(arr,2))

2
int16
int64
0.99
[0.15 0.6  0.43 0.97 0.24 0.37 0.78 0.3  0.37 0.66]


In [13]:
# 请你解释下面代码的作用
# 对数组进行基本的算术运算（加法、乘法、除法）
# 创建一个包含整数0到23的二维数组，形状为6行4列
# 原理是什么
# 广播机制
# 当对不同形状的数组进行算术运算时，NumPy会自动调整它们的形状以便进行元素级别的操作。
# 具体来说，当一个数组的维度较小且可以通过复制来匹配另一个数组的维度时，NumPy会“广播”较小的数组，使其形状与较大的数组相匹配。
# 例如，在下面的代码中，二维数组 t1 的形状为 (6, 4)，而标量值 2 可以被视为形状为 (1, 1) 的数组。通过广播机制，NumPy 会将标量 2 扩展为与 t1 形状相同的数组，从而使得加法操作得以进行。
# 这种机制使得我们能够方便地对数组进行标量运算，而无需显式地创建与数组形状相同的标量数组。
# 创建一个包含整数0到23的二维数组，形状为6行4列
t1 =np.arange(24).reshape((6,4))
print(t1+2)
print("-"*20)
print(t1*2)
print("-"*20)
print(t1/2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


In [16]:
t1 = np.arange(24).reshape((6,4))
print(t1)
t2 = np.arange(100,124).reshape((6,4))
print(t2)
print(t1+t2)
print(t1 * t2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [19]:
t1 = np.arange(24).reshape((4,6))
print(t1)
print("-" * 50)
t2 = np.arange(0,6)
print(t2)
print("-" * 50)
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------
[0 1 2 3 4 5]
--------------------------------------------------
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


In [20]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(4).reshape((4,1))
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


In [22]:
# 请你解释下面代码的作用
# 计算数组的和，指定不同的轴进行求和操作
# 创建一个包含整数1到6的二维数组，形状为2行3列
# 计算数组在不同轴上的和
# axis=0表示按列求和，axis=1表示按行求和
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a,axis=0)) # [5 7 9]
print(np.sum(a,axis = 1)) # [ 6 15]
print(np.sum(a))
a=np.arange(27).reshape((3,3,3))
print(a)
b=np.sum(a, axis=0)
print("-"*20)
print(b)
c=np.sum(a, axis=1)
print("-"*20)
print(c)
d=np.sum(a, axis=2)
print("-"*20)
print(d)

[5 7 9]
[ 6 15]
21
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------
[[27 30 33]
 [36 39 42]
 [45 48 51]]
--------------------
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
--------------------
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]


In [23]:
import numpy as np
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)
print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*'*20)
print(t1[1:])# 取连续的多行
print('*'*20)
print(t1[1:3,:])# 取连续的多行
print('*'*20)
print(t1[[0,2,3]])# 取不连续的多行
print('*'*20)
print(t1[[0,2,3],:])# 取不连续的多行
print('*'*20)
print(t1[:,1])# 取一列
print('*'*20)
print(t1[:,1:])# 连续的多列
print('*'*20)
print(t1[:,[0,2,3]])# 取不连续的多列
print('*'*20)
print(t1[2,3])# # 取某一个值,三行四列
print('*'*20)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************


In [24]:
t = np.arange( 24 ).reshape( 4, 6 )
# # 修改某一行的值
t[1, :] = 0
#
# # 修改某一列的值
t[:, 1] = 0
# # 修改连续多行
t[1:3, :] = 0
#
# # 修改连续多列
t[:, 1:4] = 0
#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:4,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[0,3]]=0
# print(t)
# 可以根据条件修改，比如讲小于 10 的值改掉
t[t < 10] = 0
# print(t)
# 使用逻辑判断
# np.logical_and & # np.logical_or |
# np.logical_not ~
t[(t > 2) & (t < 6)] = 0 # 与
t[(t < 2) | (t > 6)] = 0 # 或
t[~(t > 6)] = 0 # 非
# print(t)
t=t.clip(10,18)
print(t)
# # 拓 展
# # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出 x，不满足输出y。)）
score = np.array( [[80, 88], [82, 81], [75, 81]] )
result = np.where( score > 80, True, False )
print( result )

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[False  True]
 [ True  True]
 [False  True]]


In [25]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print('第一个数组：')
print(a)
print('\n')
print(' 向 数 组 添 加 元 素 ：')
print(np.append(a, [7, 8, 9]))
print('\n')
print('沿轴 0 添加元素：')
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')
print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))
# 2. numpy.insert
# 函数在给定索引之前，沿给定轴在输入数组中插入值。# 如果值的类型转换为要插入，则它与输入数组不同。
# 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。
a = np.array([[1, 2], [3, 4], [5, 6]])
print('第一个数组：')
print(a)
print('\n')
print('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print(np.insert(a, 3, [11, 12]))
print('\n')
print('传递了 Axis 参数。 会广播值数组来配输入数组。')

print('沿轴 0 广播：')
print(np.insert(a, 1, [11], axis=0))
print('\n')
print('沿轴 1 广播：')
print(np.insert(a, 1, 11, axis=1))

第一个数组：
[[1 2 3]
 [4 5 6]]


 向 数 组 添 加 元 素 ：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]
第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]


传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴 0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [26]:
#numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，
# 如果未提供轴参数， 则输入数组将展开。
'''参 数 说 明 ： arr： 输 入 数 组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组 axis：
沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开'''
import numpy as np
a = np.arange(12).reshape(3,4)
print('第一个数组：')
print(a)
print('\n')
print('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print(np.delete(a,5))
print('\n')
print('删除每一行中的第二列：')
print(np.delete(a,1,axis = 1))
print('\n')

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在删除之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


删除每一行中的第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]




In [27]:
# numpy.unique 函数用于去除数组中的重复元素。
'''
arr：输入数组，如果不是一维数组则会展开
return_index：如果为 true，返回新列表元素在旧列表中的位置（下标），并以列表形式储
return_inverse：如果为 true，返回旧列表元素在新列表中的位置（下标），并以列表形式储
return_counts：如果为 true，返回去重数组中的元素在原数组中的出现次数
'''
import numpy as np
a = np.array([5,2,6,2,7,5,6,8,2,9])
print ('第一个数组：')
print (a)
print ('\n')
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')
print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print (indices)
print ('\n')
print ('我们可以看到每个和原数组下标对应的数值：')
print (a)
print ('去重数组的下标：')
u,indices = np.unique(a,return_inverse = True)
print (u)
print (indices)
print ('\n')
print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)

第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]


去重数组的索引数组：
[1 0 2 4 7 9]


我们可以看到每个和原数组下标对应的数值：
[5 2 6 2 7 5 6 8 2 9]
去重数组的下标：
[2 5 6 7 8 9]
[1 0 2 0 3 1 2 4 0 5]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


In [28]:
import numpy as np
score = np.array([[80,88],[82,81],[75,81]])
# 1. 获取所有数据最大值
result = np.max(score)
print(result)
# 2. 获取某一个轴上的数据最大值
result = np.max(score,axis=0)
print(result)
# 3. 获取最小值
result = np.min(score)
print(result)
# 4. 获取某一个轴上的数据最小值
result = np.min(score,axis=0)
print(result)
# 5. 数据的比较
result = np.maximum( [-2, -1, 0, 1, 2], 0 ) # 第一个参数中的每一个数与第二个参数比较返回大的
print(result)
result = np.minimum( [-2, -1, 0, 1, 2], 0 ) # 第一个参数中的每一个数与第二个参数比较返回小的
print(result)
result = np.maximum( [-2, -1, 0, 1, 2], [1, 2, 3, 4, 5] )
print(result)
# 接受的两个参数，也可以大小一致;第二个参数只是一个单独的值时，其实是用到了维度的广播机制；
# 6. 求平均值
result = np.mean(score) # 获取所有数据的平均值
print(result)
result = np.mean(score,axis=0) # 获取某一行或者某一列的平均值
print(result)
# 7. 求前缀和
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print(arr.cumsum(0))
'''
[1, 2, 3]------> |1 |2 |3 |
[4, 5, 6]------> |5=1+4 |7=2+5 |9=3+6|
'''
print(arr.cumsum(1))
'''
[1, 2, 3]------> |1 |2+1 |3+2+1 |
[4, 5, 6]------> |4 |4+5 |4+5+6 |
'''
# 8. argmin 求最小值索引

result = np.argmin(score,axis=0)
res=np.min(score,axis=0) #这样我们就可以知道最小的 81 是第二排的，是从前往后遍历的
print(result,res)
# 9. 求每一列的标准差（这里是总体标准差）
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值之间差异较大；
# 一个较小的标准差，代表这些数据较接近平均值反应出数据的波动稳定情况，越大表示波动越大，越不稳定。
result = np.std(score,axis=0)
print(result)
# 10. 极 值
result = np.ptp(score,axis=None)#就是最大值和最小值的差
print(result)
# 拓展：方差 var, 协方差 cov, 计算平均值 average, 计算中位数 median

88
[82 88]
75
[75 81]
[0 0 0 1 2]
[-2 -1  0  0  0]
[1 2 3 4 5]
81.16666666666667
[79.         83.33333333]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]
[2 1] [75 81]
[2.94392029 3.29983165]
13


In [30]:
# 有的时候我们需要将两个数据加起来一起研究分析，我们就可以将其进行拼接然后分析
import numpy as np
# 1. 根据轴连接的数组序列
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
# 要求 a,b 两个数组的维度相同
print ('沿轴 0 连接两个数组：')
print (np.concatenate((a,b),axis= 0))
print ('\n')
print ('沿轴 1 连接两个数组：')
print (np.concatenate((a,b),axis = 1))
# 2. 根据轴进行堆叠
print ('沿轴 0 连接两个数组：')
print (np.stack((a,b),axis= 0))
print ('\n')
print ('沿轴 1 连接两个数组：')
print (np.stack((a,b),axis = 1))
# 3. 矩阵垂直拼接
v1 = [[0,1,2,3,4,5],
[6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],
[18,19,20,21,22,23]]
result = np.vstack((v1,v2))
print(result)
# 4. 矩阵水平拼接
v1 = [[0,1,2,3,4,5],
[6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],
[18,19,20,21,22,23]]
result = np.hstack((v1,v2))
print(result)

沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]
沿轴 0 连接两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


沿轴 1 连接两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


In [31]:
# 1. 将一个数组分割为多个子数组
'''参数说明：
ary：被分割的数组
indices_or_sections：是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置
（左开右闭）
axis：沿着哪个维度进行切向，默认为 0，横向切分。为 1 时，纵向切分
'''
import numpy as np
arr = np.arange(9).reshape(3,3)
print ('将数组分为三个大小相等的子数组：')
b = np.split(arr,3)
print (b)
# 2.numpy.hsplit 函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组。
harr = np.floor(10*np.random.random((2, 6)))
print ('原 array：')
print(harr)
print ('拆分后：')
print(np.hsplit(harr, 3))
# 3.numpy.vsplit 沿着垂直轴分割
a = np.arange(16).reshape(4,4)
print ('第一个数组：')
print (a)
print ('\n')
print ('竖直分割：')
b = np.vsplit(a,2)
print (b)


将数组分为三个大小相等的子数组：
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
原 array：
[[3. 9. 5. 0. 6. 0.]
 [3. 2. 3. 4. 5. 5.]]
拆分后：
[array([[3., 9.],
       [3., 2.]]), array([[5., 0.],
       [3., 4.]]), array([[6., 0.],
       [5., 5.]])]
第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


竖直分割：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [32]:
'''
C 语言中表示最大的正整数值是 0x7FFF FFFF，最小的负整数是 0x8000 0000。
查阅资料后，发现 inf 表示无穷大，需要使用 float(‘inf’) 函数来转化，那么对应的就有
float('-inf') 表示无穷小了。
这样你就可以使用任意数来判断和它的关系了。
那什么时候会出现 inf 呢？ 比如一个数字除以 0，Python 中会报错，但是 numpy 中会是一个
inf
或者-inf
另外还有 nan，这种写法在 pandans 中常见，表示缺失的数据，所以一般用 nan 来表示。
任何与其做运算结果都是 nan（比如零除以零，在 numpy 中）
'''
import numpy as np
# 创建一个 nan 和 inf #
a = np.nan
b = np.inf
print(a,type(a))
print(b,type(b))

nan <class 'float'>
inf <class 'float'>


In [33]:
# --判断数组中为 nan 的个数
t = np.arange(24,dtype=float).reshape(4,6)
# 将三行四列的数改成 nan
t[3,4] = np.nan
# 可以使用 np.count_nonzero() 来判断非零的个数
print(np.count_nonzero(t))
# 并 且 np.nan != np.nan 结果 是 TRUE
# 所以我们可以使用这两个结合使用判断 nan 的个数
print(np.count_nonzero(t != t))
# 将 nan 替换为 0
t[np.isnan(t)] = 0
print(t)

23
1
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [38]:
import numpy as np

t = np.arange(24).reshape(4,6).astype('float')
t[1, 3:] = np.nan
print(t)
print('-------------------')

for i in range(t.shape[1]):
    temp_col = t[:, i]              # 视图（或切片）
    if np.count_nonzero(~np.isnan(temp_col)) == 0:
        # 整列均为 NaN，跳过或按需处理
        continue
    col_mean = np.nanmean(temp_col) # 忽略 NaN 计算平均值
    temp_col[np.isnan(temp_col)] = col_mean
    t[:, i] = temp_col              # 显式写回（切片通常是视图，写回以防万一）

print(t)


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
-------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
